[phases.setup]
aptPkgs = [
  "chromium-browser",
  "chromium-codecs-ffmpeg",
  "libnss3",
  "libxss1",
  "libasound2",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libgbm1",
  "libgtk-3-0",
  "libxshmfence1",
  "fonts-noto-color-emoji",
  "ca-certificates",
  "fonts-liberation",
  "libdrm2",
  "libglib2.0-0",
  "libnspr4"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
NODE_ENV = "production"

[phases.build]
cmds = [
  "npm install",
  "npm run build"
]