[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "libxslt",
  "libxml2", 
  "libpng",
  "libxcb",
  "libX11",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXi",
  "libXrandr",
  "libXrender",
  "libXtst",
  "libxshmfence",
  "libgbm",
  "libgcc",
  "glib",
  "nspr",
  "atk",
  "at-spi2-atk",
  "libdrm",
  "expat",
  "mesa",
  "pango",
  "cairo"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "1"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/chrome-linux/chrome"