[phases.setup]
aptPkgs = [
  "chromium",
  "libnss3",
  "libxss1",
  "libasound2",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libgtk-3-0",
  "libgbm1",
  "libxshmfence1",
  "fonts-noto-color-emoji"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NODE_ENV = "production"